import './globals.css'

import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { MAX_MOBILE_SCREEN_WIDTH } from '@/config/constants'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  /**
   * **iOS의 "safe area"**를 사용하는 데 영향을 미치는 속성.
   * cover 를 설정하면 콘텐츠가 디바이스의 모든 화면 영역을 커버하며, 노치 영역까지 포함됩니
   *
   */
  viewportFit: 'cover',
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://cdn.jsdelivr.net"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main
          className="mx-auto h-full min-h-screen border-r-1 border-l-1 border-gray-800 bg-[#EEEDDE]"
          style={{
            maxWidth: MAX_MOBILE_SCREEN_WIDTH,
          }}
        >
          {children}
        </main>
      </body>
    </html>
  )
}
